config/routes.rb
Rails.application.routes.draw do
  get 'invoices/show'
  get 'invoices/index'
  get 'clients/show'
  get 'clients/index'
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:show] 
  resources :clients
  resources :invoices do
    resources :items, only: [:new, :create, :index]
  end 


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  validates :name, presence: :true
  # validates :address, presence: :true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  validates :date, presence: :true
  validates :object, presence: :true

  has_one :selected_client
  has_one :client, through: :selected_client

  has_many :items



end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice
end

app/models/selected_client.rb
class SelectedClient < ApplicationRecord
  belongs_to :invoice, optional: true
  belongs_to :client, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :iban, :bic, :siren, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :iban, :bic, :siren, :photo])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all.where(user_id: current_user)
  end

  def show 
    @client = Client.find(params[:id])
  end


  def new
    @client = Client.new
  end 

  def create
    @client = Client.new(client_params)
    @client.user = current_user
    @client.save!
    flash.alert = "New client added"

    redirect_to client_path(@client)
  end

  def edit
    @client = Client.find(params[:id])

  end

  def update
    # @client = Client.find(params[:id])
    # if @client.update(client_params.reject { |k| k["photos"] })
    #   if client_params[:photos].present?
    #     client_params[:photos].each do |photo|
    #       @client.photos.attach(photo)
    #     end
    #   end
    #   flash.alert = "Projet Modifié"
    #   redirect_to articles_path(@client)
    # else
    #   flash.alert = "Projet non modifié"
    #   redirect_to articles_path
    # end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    flash.alert = "Client deleted"
    redirect_to clients_path
  end

  private 

  def client_params 
    params.require(:client).permit(:name, :address)
  end 

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all.where(user_id: current_user)
  end

  def show 
    @invoice = Invoice.find(params[:id])
    @selected_client = SelectedClient.find_by(invoice_id: @invoice)
    @items = Item.where(invoice_id: @invoice.id)

    respond_to do |format|
      format.html
      format.pdf do
        # Rails 6:
        # render template: "posts/show.html.erb",
        #        pdf: "Post ID: #{@post.id}"

        # Rails 7:
        # render pdf: "file_name", template: "invoices/show",

        render(
          pdf: 'document',
          formats: [:html],
          encoding: 'UTF-8',
          template: 'invoices/show',
          layout: 'pdf',
          margin: {
            top: 16, # default 10 (mm)
            bottom: 16
          }
        )
        

      end
    end
  end


  def new
    @number_of_invoices = Invoice.all.where(user_id: current_user).length
    @invoice = Invoice.new
    @item = Item.new
    @clients = Client.all.where(user_id: current_user)
  end 

  def create

    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user
    @client = Client.find(params[:invoice][:client])

    @selected_client = SelectedClient.new
    @selected_client.client = @client
    @selected_client.invoice = @invoice
    @selected_client.save!

    @invoice.selected_client = @selected_client


    @invoice.save!

    flash.alert = "New invoice added"

    redirect_to new_invoice_item_path(@invoice)
  end

  def edit
    @invoice = Invoice.find(params[:id])

  end


  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    flash.alert = "Invoice deleted"
    redirect_to invoices_path
  end

  private 

  def invoice_params 
    params.require(:invoice).permit(:object, :date)
  end 

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index 
    @invoice = Invoice.find(params[:invoice_id])
    @items = Item.all.where(invoice_id: params[:invoice_id])
  end

  def new
    @item = Item.new
    @invoice = Invoice.find(params[:invoice_id])
  end 

  def create 
    @invoice = Invoice.find(params[:invoice_id])
    @item = Item.new(items_params)
    @item.invoice = @invoice
    @item.total = @item.quantity.to_i * @item.price.to_i
    @item.save!
    flash.alert = "Item Ajouté"
    redirect_to invoice_items_path(@invoice)
  end 


  private 

  def items_params 
    params.require(:item).permit(:name, :quantity, :unit, :price)
  end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def invoice_number(invoice)
    first_name = invoice.user.first_name[0]
    last_name = invoice.user.last_name[0]
    initials = "#{first_name}#{last_name}"
    invoices_count = Invoice.where(user_id: current_user).count
    if invoices_count < 10
      invoice_num = "0#{invoices_count}"
    else 
      invoice_num = invoices_count
    end
    return "F#{invoice.date.strftime("%Y%m%d")}#{initials}#{invoice_num}"
  end 

  def total_price_per_item(quantity, price)
    return quantity.to_i * price.to_i
  end

  def total_price(array_items)
    total = 0
    array_items.each do |item|
      total += item.total
    end
    return total
  end
end

app/views/clients/index.html.erb
<div class="container">
  <h1>Clients#index</h1>
  <% @clients.each do |client| %>
   <p><%= client.name %></p> 
  <% end %>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between border-bottom my-4">
    <h3 class="d-none-xs">New Client</h3>
    <h3>Add a client</h3>
  </div>
  <%= simple_form_for((@client), data: {turbo: false}) do |f| %>
    <%= f.input :name, label:"Titre" %>
    <%= f.input :address,
                    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
                    required: true
    %>
    <%= f.submit "Ajouter le projet", class:"btn-primary" %>
  <% end %>
</div>

app/views/clients/show.html.erb
<div class="container">
  <h1>Your Client</h1>
  <h2><%= @client.name %></h2>
  <p><%= @client.address %></p>
</div>

app/views/invoices/index.html.erb
<div class="container">
  <h1>My Invoices#index</h1>
  <h2>
    <% if @number_of_invoices == 0 %>
      <h2>Add clients before invoicing!</h2>
    <% end %>
  </h2>
  <% @invoices.each do |invoice| %>
    <%= link_to invoice.object, invoice_path(invoice) %>

    <h1>PDF</h1>
    <%= link_to invoice.object, invoice_path(invoice, format: :pdf) %>

    <%= invoice.selected_client.client.name %>
  <% end %>
</div>

app/views/invoices/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between border-bottom my-4">
    <h3 class="d-none-xs">New Invoice</h3>
    <h3>Add an invoice</h3>
  </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>1/ Créer sa facture</h1>
      <%= simple_form_for((@invoice), data: {turbo: false}) do |f| %>
        <%= f.input :object, label:"Object" %>
        <%= f.input :date, label:"Date" %>
        <%= f.input :client, label: false, collection: @clients, prompt: 'Select a client' %>
        <%= f.submit "Créer la facture", class:"button button-primary" %>
      <% end %>
    </div>
  
  </div>
</div>

app/views/invoices/show.html.erb
<div class="container container-invoice">
  <div class=" d-flex justify-content-between">
    <div>
      <% if current_user.photo.attached? %>
        <%= image_tag current_user.photo %>
      <% end %>
      <p><%= current_user.first_name %><%= current_user.last_name %></p>
      <p><%= current_user.address %></p>
      <strong><p id="invoice-object">Objet : <%= @invoice.object %></p></strong>
    </div>
    <div class="text-end">
      <p>Facture n° <%= invoice_number(@invoice) %></p>
      <p><%= @invoice.date.strftime("%d/%m/%Y") %></p>
      <p><%= @invoice.selected_client.client.name %></p>
      <p><%= @invoice.selected_client.client.address %></p>
    </div>
  </div>

  <div class="row justify-content-center table-row">
    <div class="col-2"><strong><p>Référence</p></strong></div>
    <div class="col-2"><strong><p>Désignation</p></strong></div>
    <div class="col-2"><strong><p>Quantité</p></strong></div>
    <div class="col-2"><strong><p>Unité</p></strong></div>
    <div class="col-2"><strong><p>PU HT</p></strong></div>
    <div class="col-2"><strong><p>TOTAL HT</p></strong></div>  
  </div>
  <div class="row justify-content-center table-items">
    <% @items.each do |item| %>
        <div class="col-2"><p><%= item.id %></p></div>
        <div class="col-2"><p><%= item.name %></p></div>
        <div class="col-2"><p><%= item.quantity %></p></div>
        <div class="col-2"><p><%= item.unit %></p></div>
        <div class="col-2"><p><%= item.price %></p></div>
        <div class="col-2"><p><%= total_price_per_item(item.quantity, item.price) %></p></div>  
    <% end %>
  </div>

  <div>
    <div class="row justify-content-end table-items">
      <div class="col-2"><p>Montant HT</p></div>
      <div class="col-2"> <%= total_price(@items) %></div>
    </div>
    <div class="row justify-content-end table-items">
      <div class="col-2"><p>Montant Total TTC</p></div>
      <div class="col-2"> <%= total_price(@items) %></div>
    </div>
    <div class="row justify-content-end table-items">
      <div class="col-2"><strong><p>Reste à payer</p></strong></div>
      <div class="col-2"><strong> <%= total_price(@items) %></strong></div>
    </div>
  
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between border-bottom my-4">
    <h3 class="d-none-xs">Facture n°<%= invoice_number(@invoice) %></h3>
    <h3>Liste des éléments</h3>
  </div>
  <div class="row justify-content-center">
    <div class="col-2"><strong><p>Référence</p></strong></div>
    <div class="col-2"><strong><p>Désignation</p></strong></div>
    <div class="col-2"><strong><p>Quantité</p></strong></div>
    <div class="col-2"><strong><p>Unité</p></strong></div>
    <div class="col-2"><strong><p>PU HT</p></strong></div>
    <div class="col-2"><strong><p>TOTAL HT</p></strong></div>  
  </div>
  <div class="row justify-content-center">
    <% @items.each do |item| %>
      <div class="col-2"><strong><p><%= item.id %></p></strong></div>
      <div class="col-2"><strong><p><%= item.name %></p></strong></div>
      <div class="col-2"><strong><p><%= item.quantity %></p></strong></div>
      <div class="col-2"><strong><p><%= item.unit %></p></strong></div>
      <div class="col-2"><strong><p><%= item.price %></p></strong></div>
      <div class="col-2"><strong><p><%= total_price_per_item(item.quantity, item.price) %></p></strong></div>  
    <% end %>
  </div>
  <div class="d-flex justify-content-between">
    <div class="button button-primary" id="new_item_button"  >
      <%= link_to "+ Ajouter un nouvel élément", new_invoice_item_path(@invoice)%>
    </div>
    <div class="button button-primary" id="new_item_button"  >
      <%= link_to "Voir la facture finale", invoice_path(@invoice)%>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between border-bottom my-4">
    <h3 class="d-none-xs">New Item</h3>
    <h3>Add an item</h3>
  </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>2/ Ajouter des éléments</h1>
      <%= simple_form_for([@invoice, @item], data: {turbo: false}) do |f| %>
        <%= f.input :name, label:"Désignation" %>
        <%= f.input :quantity, label:"Quantité" %>
        <%= f.input :unit, label:"Unité" %>
        <%= f.input :price, label:"Prix" %>
        <%= f.submit "Ajouter un item", class:"button button-primary" %>
      <% end %>

    </div>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facturier</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>

    

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body onload='number_pages'>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%# <div id="header"> %>
      <%# <%= wicked_pdf_image_tag 'mysite.jpg' %> 
    <%# </div> %>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='UTF-8' />
    <%= stylesheet_link_tag wicked_pdf_asset_base64("pdf") %>
  </head>
  <body onload='number_pages'>
    <div id="header">
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex home-container">
  <div class="banner-left">
  </div>
  <div class="p-5 d-flex flex-column align-items-center banner-right">
    <h1>Girl Boss' Invoicer</h1>
    <%= link_to 'My clients', clients_path, class:"button button-second w-100 m-2" %>
    <%= link_to 'My invoices', invoices_path, class:"button button-second w-100 m-2" %>
    <%= link_to 'New Client', new_client_path, class:" button button-primary w-100 m-2" %>
    <%= link_to 'New Invoice', new_invoice_path, class:" button button-primary w-100 m-2" %>
    <div>
      <h2 class="mt-2">KPI</h2>
      <p><%= Invoice.all.where(user_id: current_user).length %> invoices issued</p>
      <p>X$ generated !</p>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to "Home", root_path, class:"button button-primary" %>
  <% if current_user && current_user.photo.attached? %>
    <%= link_to user_path(current_user) do  %>
      <%= image_tag current_user.photo %>
      <% unless current_user.photo.attached? %>
        <p>My profile</p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <p><%= @user.first_name %> <%= @user.last_name %></p>
      <p><%= @user.address %></p>
      <p>IBAN : <%= @user.iban %> BIC : <%= @user.bic %></p>
      <p>SIREN : <%= @user.siren %></p>
    </div>
  </div>
</div>